[common]
open = "Open"
reset = "Reset"

[errors]
translate_fail = "Translation failed"

[home]
title = "Home"
welcome = "Welcome back,"
version = "Installed version"
time = "Play time"
last = "Last played"

[play]
install = "Install"
update = "Update"
play = "Play"
version = "Version"
total = "Total downloads"
prerelease = "Enable Pre-release"

[settings]
title = "Settings"
language = "Language"
translate = "Translate changelog - Google Translate"
darkmode = "Use darkmode"
scale = "Scale"
remember = "Remember window size & position"
backgroundm = "Disable background music"
openp86 = "Open 86-Project folder"
openl = "Open launcher folder"
openlog = "Open logs folder"
resetd = "Reset data"
resetc = "Reset cache"

[about]
title = "About"
content = "A Launcher developed for Project-86-Community-Game for managing game files."
license = """Background music: "Project: 86 OST: Legion" by XYETRY.

 Project-86-Launcher: A Launcher developed for Project-86-Community-Game for managing game files.
 Copyright (C) 2025 Project 86 Community

 This program is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 This program is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with this program.  If not, see <https://www.gnu.org/licenses/>."""
