[common]
open = "Open"

[home]
title = "Home"
welcome = "Welcome back,"
downloaded = "Downloaded:"
playtime = "Play time:"
lastplayed = "Last played:"
version = "Latest version:"
downloads = "Downloads:"

[play]
title = "Play"
install = "Install"
prerelease = "Install Pre-release"
update = "Update"
launcher = "Update Launcher"
play = "Play"

[changelog]
title = "Changelog"
view = "View"

[settings]
title = "Settings"
locale = "Language"
colormode = "Change Launcher to dark-mode"
appscale = "Change Launcher scale"
prerelease = "Use Pre-release"
company = "Open Project86 directory"
launcher = "Open Launcher directory"
resetdata = "Reset data"
resetcache = "Reset cache"

[about]
title = "About"
lead = "Lead developer - Taliayaya"
dev = "Launcher developer - Sky"
info = "Welcome to Project 86 - a fan game in its early stages, with the primary goal of delivering a functional beta swiftly. We invite players to actively participate and provide feedback, steering the game in the right direction."

